### 리스트의 활용

In [18]:
# 여기 빈 리스트가 있습니다.
number_list = []

# number_list에 1부터 100까지 수를 거꾸로 넣어보세요
# 예: 100, 99, 98, ... 3, 2, 1
for i in range(0,100) :
    number_list.append(100 - i) # append : 잡어넣는거
    
# number_list에서 10번째, 30번째, 50번째 원소를 각각 출력해봅시다
print(number_list[9]) # 10번째 원소
print(number_list[29]) # 30번째 원소
33 print(number_list[49]) # 50번째 원소

91
71
51


### 나만의 함수 만들기

In [21]:
# 입력 숫자
input_num = 10
# 숫자 데이터를 넣었을 때 10배로 되돌려주는 함수
def my_function(a):
    return (a * 10)

# my_function을 사용하여 result에 값을 저장합니다.
result = my_function(input_num)

# 최종 결과값을 출력합니다.
print(result)

100


### pandas 기본(1)

In [22]:
import pandas as pd

# 코로나 엑셀 데이터 파일(.xlsx)이 저장된 경로입니다.
#data_path = './data/corona_data.xlsx'

# pandas를 활용해 엑셀 파일을 불러오고, corona_data에 저장합니다.
#corona_data = pd.read_excel(data_path)

# corona_data셋에서 '확진자' 데이터만 추출하여 출력해보세요
#confirmed = corona_data['확진자']
#print(confirmed)

### pandas 기본(2)

.loc[행 지정, 열 지정]이다<br>
df.loc[df['과일']=='사과','가격'] 이면 과일 열 값이 사과인 행의 가격만 표시하게 되는 것

In [23]:
import pandas as pd

# 코로나 데이터를 불러옵니다.
#data_path = './data/corona_data.xlsx'
#corona_data = pd.read_excel(data_path)

# 확진자가 10000명 이상인 시점부터의 모든 데이터를 추출합니다.
#confirmed_10000 = corona_data.loc[corona_data['확진자']>=10000 , :] # : 이면 모든 행 열
#print(confirmed_10000)

머신러닝 = 명시적으로 프로그래밍을 하지 않고도 컴퓨터가 학습할 수 있는 능력을 갖게 하는것

기계학습 - 지도학습     - 회귀 분석
                   - 분류
                        
                        
                        
         - 비지도학습   - 클러스터링
    
         - 강화학습

In [25]:
import numpy as np
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

### Numpy 

Numpy library에서 자주 사용되는 함수<br>
np.array - 배열생성<br>
np.zeros - 0이 들어있는 배열 생성<br>
np.ones - 1이 들어있는 배열 생성<br>
np.empty - 초기화가 없는 값으로 배열을 반환<br>
np.arange(n) - 배열 버전의 range 함수<br>
np.random.randint - 다양한 난수가 들어있는 배열 생성<br>

In [26]:
arr = np.arange(7)
arr[1:3]

array([1, 2])

In [35]:
import numpy as np

print("1차원 array")
array = np.arange(10)
print(array)

# Q1. array의 자료형을 출력해보세요.
type(array)

# Q2. array의 차원을 출력해보세요.
array.ndim

# Q3. array의 모양을 출력해보세요.
array.shape

# Q4. array의 크기를 출력해보세요.
array.size

# Q5. array의 dtype(data type)을 출력해보세요.
array.dtype

# Q6. array의 인덱스 5의 요소를 출력해보세요.
array[5]

# Q7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
array[3:6]


1차원 array
[0 1 2 3 4 5 6 7 8 9]


array([3, 4, 5])

In [36]:
import numpy as np

print("2차원 array")
matrix = np.arange(1, 16).reshape(3,5)  #1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
print(matrix)


# Q1. matrix의 자료형을 출력해보세요.
print(type(matrix))

# Q2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# Q3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# Q4. matrix의 크기를 출력해보세요.
print(matrix.size)

# Q5. matrix의 dtype(data type)을 출력해보세요.
print(matrix.dtype)

# Q6. matrix의 (2,3) 인덱스의 요소를 출력해보세요.
print(matrix[2,3])

# Q7. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2,1:4])



2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int32
14
[[2 3 4]
 [7 8 9]]


In [37]:
# 모양을 바꿔주는 함수 reshape
import numpy as np

print("array")
array = np.arange(8)
print(array)
print("shape : ", array.shape, "\n")

# Q1. array를 (2,4) 크기로 reshape하여 matrix에 저장한 뒤 matrix와 그의 shape를 출력해보세요.
print("# reshape (2, 4)")
matrix =array.reshape(2,4)


print(matrix)
print("shape : ", matrix.shape)


array
[0 1 2 3 4 5 6 7]
shape :  (8,) 

# reshape (2, 4)
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4)


In [38]:
# 이어 붙이는 concatenate axis = 0 : 세로 axis = 1 : 가로
import numpy as np

print("matrix")
matrix = np.array([[0,1,2,3],
                   [4,5,6,7]])
print(matrix)
print("shape : ", matrix.shape, "\n")

# (아래의 배열 모양을 참고하세요.)
# Q1. matrix 두 개를 세로로 붙이기 
'''
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
'''

m = np.concatenate([matrix,matrix], axis = 0)
print(m)

#matrix = np.array([[0,1,2,3],[4,5,6,7],[0,1,2,3],[4,5,6,7]])
#print(matrix)

# Q2. matrix 두 개를 가로로 붙이기
'''
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]
'''

n = np.concatenate([matrix,matrix],axis = 1)
print(n)


matrix
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4) 

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


In [39]:
# 배열 분할 함수 : split
import numpy as np

print("matrix")
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
print(matrix, "\n")

# Q1. matrix를 [3] 행에서 axis 0으로 나누기
'''
[[0  1   2  3]
 [4  5   6  7]
 [8  9  10 11]],

 [12 13 14 15]
'''

a, b = np.split(matrix,[3], axis=0)

print(a, "\n")
print(b, "\n")


# Q2. matrix를 [1] 열에서 axis 1로 나누기
'''
[[ 0]
 [ 4]
 [ 8]
 [12]],

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
'''

c, d = np.split(matrix, [1], axis = 1) 

print(c, "\n")
print(d)

matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]] 

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [40]:
# Numpy 연산
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

# Q1. array에 5를 더한 값을 출력해보세요.
print(array + 5)

# Q2. array에 5를 뺀 값을 출력해보세요.
print(array - 5)

# Q3. array에 5를 곱한 값을 출력해보세요.
print(np.dot(array,5))

# Q4. array를 5로 나눈 값을 출력해보세요.
print(array / 5)

# Q5. array에 array2를 더한 값을 출력해보세요.    
array2 = np.array([5,4,3,2,1])
print(array + array2)

# Q6. array에 array2를 뺀 값을 출력해보세요.
print(array - array2)


[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[6 6 6 6 6]
[-4 -2  0  2  4]


넘파이로 생성한 배열으 크기가 다를 경우 연산을 하게 되면 브로드캐스팅이라는 연산 방식으로 넘파이를 처리한다.

In [41]:
# 브로드캐스팅 
import numpy as np

'''
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]] 배열 A와

 [0 1 2 3 4 5] 배열 B를 선언하고, 덧셈 연산해보세요.
'''

A = np.arange(6).reshape(6,1)
B = np.arange(6).reshape(1,6)

print(A + B)

[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


In [43]:
# 집계함수
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)

# Q1. sum 함수로 matrix의 총 합계를 구해 출력해보세요.

print(matrix.sum())

# Q2. max 함수로 matrix 중 최댓값을 구해 출력해보세요.

#print(matrix.max())
print(np.max(matrix))

# Q3. min 함수로 matrix 중 최솟값을 구해 출력해보세요.
#print(matrix.min())
print(np.min(matrix))

# Q4. mean 함수로 matrix의 평균값을 구해 출력해보세요.

#print(matrix.mean())
print(np.mean(matrix))

# Q5. sum 함수의 axis 매개변수로 각 열의 합을 구해 출력해보세요.

print(np.sum(matrix,axis = 0))
# Q6. sum 함수의 axis 매개변수로 각 행의 합을 구해 출력해보세요.
print(np.sum(matrix,axis = 1))

# Q7. std 함수로 matrix의 표준편차를 구해 출력해보세요.

print(np.std(matrix))

# Q8. 마스킹 연산을 이용하여 matrix 중 5보다 작은 수들만 추출하여 출력해보세요.
# 마스킹 연산 = 필요한 부분만 추출하는 연산 
print(matrix[matrix<5])


[[0 1 2 3]
 [4 5 6 7]]
28
7
0
3.5
[ 4  6  8 10]
[ 6 22]
2.29128784747792
[0 1 2 3 4]


In [44]:

import numpy as np

daily_liar_data = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]


# 0이 몇 개 있는지 구하여 출력해주세요.

def main() :
    # 해당하는 코드 작성
    a = np.array(daily_liar_data)
    print(np.count_nonzero(a == 0))



if __name__ == "__main__" :
    main()

71


### Pandas

In [45]:
import numpy as np
import pandas as pd

# 예시) 시리즈 데이터를 만드는 방법.
series = pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'], name="Title")
print(series, "\n")


# 국가별 인구 수 시리즈 데이터를 딕셔너리를 사용하여 만들어보세요.

country = pd.Series({'korea':5180, 'japan':12718, 'china':141500, 'usa':32676})
print(country)

a    1
b    2
c    3
d    4
Name: Title, dtype: int64 

korea      5180
japan     12718
china    141500
usa       32676
dtype: int64


In [63]:
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터가 있습니다.
print("Population series data:")
population_dict = {
    'korea': 5180,
    'japan': 12718,
    'china': 141500,
    'usa': 32676
}
population = pd.Series(population_dict)
print(population, "\n")

print("GDP series data:")
gdp_dict = {
    'korea': 169320000,
    'japan': 516700000,
    'china': 1409250000,
    'usa': 2041280000,
}
gdp = pd.Series(gdp_dict)
print(gdp, "\n")


# 이곳에서 2개의 시리즈 값이 들어간 데이터프레임을 생성합니다.
print("Country DataFrame")
country = pd.DataFrame({'population':population, 'gdp':gdp})
print(country)

#country.columns

# 데이터 프레임에 gdp per capita 칼럼을 추가하고 출력합니다.

gdp_per_capita = country['gdp'] / country['population']
country['gdp_per_capita'] = gdp_per_capita
print(country)

# 데이터 프레임을 만들었다면, index와 column도 각각 확인해보세요.
print(country.index)
print(country.columns)

Population series data:
korea      5180
japan     12718
china    141500
usa       32676
dtype: int64 

GDP series data:
korea     169320000
japan     516700000
china    1409250000
usa      2041280000
dtype: int64 

Country DataFrame
       population         gdp
korea        5180   169320000
japan       12718   516700000
china      141500  1409250000
usa         32676  2041280000
       population         gdp  gdp_per_capita
korea        5180   169320000    32687.258687
japan       12718   516700000    40627.457147
china      141500  1409250000     9959.363958
usa         32676  2041280000    62470.314604
Index(['korea', 'japan', 'china', 'usa'], dtype='object')
Index(['population', 'gdp', 'gdp_per_capita'], dtype='object')


In [66]:
# 데이터 프레임에서 china 출력, loc : 행
print(country.loc['china'])
#데이터 프레임에서 1부터 3 인덱스 출력, iloc :열
print(country.iloc[1:4])

population        1.415000e+05
gdp               1.409250e+09
gdp_per_capita    9.959364e+03
Name: china, dtype: float64
       population         gdp  gdp_per_capita
japan       12718   516700000    40627.457147
china      141500  1409250000     9959.363958
usa         32676  2041280000    62470.314604


In [67]:
import numpy as np
import pandas as pd

print("DataFrame: ")
df = pd.DataFrame({
    'col1' : [2, 1, 9, 8, 7, 4],
    'col2' : ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col3': [0, 1, 9, 4, 2, 3],
})
print(df, "\n")


# 정렬 코드 입력해보기    
# Q1. col1을 기준으로 오름차순으로 정렬하기.

sorted_df1 = df.sort_values('col1', ascending=True)


# Q2. col2를 기준으로 내림차순으로 정렬하기.

sorted_df2 = df.sort_values('col2', ascending=False)

# Q3. col2를 기준으로 오름차순으로, col1를 기준으로 내림차순으로 정렬하기.

sorted_df3 = df.sort_values(['col2','col1'], ascending=[True,False])


DataFrame: 
   col1 col2  col3
0     2    A     0
1     1    A     1
2     9    B     9
3     8  NaN     4
4     7    D     2
5     4    C     3 

